server:
  port: 8080
spring:
  aop:
    proxy-target-class: true
    auto: true
  datasource:
    druid:
      db2:
        url: jdbc:oracle:thin:@//10.1.0.252:1521/longeypdb
        username: longey
        password: dswybs
        driver-class-name: oracle.jdbc.OracleDriver
        initialSize: 5
        minIdle: 5
        maxActive: 20
      db1:
        url: jdbc:oracle:thin:@//127.0.0.1:1521/orcl
        username: xubo
        password: xubopassword
        driver-class-name: oracle.jdbc.OracleDriver
        initialSize: 5
        minIdle: 5
        maxActive: 20
  profiles:
    include: redis
mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: cn.sm.com.domain #实体类别名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: flag  #全局逻辑删除字段值 3.3.0开始支持，详情看下面。
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
# Swagger界面内容配置
swagger:
  title: TMax API接口文档
  description: TMax Api Documentation
  version: 1.0.0
  termsOfServiceUrl: https://www.sscai.club
  contact:
    name: niceyoo
    url: https://www.sscai.club
    email: apkdream@163.com

